
CREATE TABLE Users(
Id INTEGER PRIMARY KEY AUTOINCREMENT,
Name TEXT,
Role TEXT,
PasswordHash TEXT
);

CREATE TABLE Projects(
Id INTEGER PRIMARY KEY AUTOINCREMENT,
Name TEXT,
BillingFormula TEXT
);

CREATE TABLE ProjectFields(
Id INTEGER PRIMARY KEY AUTOINCREMENT,
ProjectId INTEGER,
Label TEXT,
Type TEXT,
Required INTEGER,
BillingField INTEGER
);

CREATE TABLE WorkReports(
Id INTEGER PRIMARY KEY AUTOINCREMENT,
UserId INTEGER,
ProjectId INTEGER,
ObjectId TEXT,
Date TEXT,
BillingAmount REAL
);

CREATE TABLE Attendance(
Id INTEGER PRIMARY KEY AUTOINCREMENT,
UserId INTEGER,
Date TEXT,
Status TEXT
);

CREATE TABLE LeaveRequests(
Id INTEGER PRIMARY KEY AUTOINCREMENT,
UserId INTEGER,
StartDate TEXT,
EndDate TEXT,
Status TEXT
);

CREATE TABLE QualityReports(
Id INTEGER PRIMARY KEY AUTOINCREMENT,
UserId INTEGER,
Score REAL,
ErrorRate REAL,
Date TEXT
);
